### ISSUE TITLE
Academic reference to csv2bib

### ISSUE THREAD

**Issue by zxxz** [jacksonpradolima/csv2bib#4]
Hello @jacksonpradolima ,

I am using your library for my Master Thesis in Enterprise Architecture and I would like to credit you and your library (and thank you!).

What would be the most academic way to reference this repository in my document?

Thanks,
Giovanni

**Comment by jacksonpradolima** [comment]
Hi @zxxz 

Thanks \o/ I am glad that **csv2bib** is helping researchers around the world. 

I updated the README with a example (in bibtex) to cite this repository.

Best Regards,
Jackson Antonio do Prado Lima.
