### ISSUE TITLE
Primeiro item do CSV

### ISSUE THREAD

**Issue by josueresende** [jacksonpradolima/csv2bib#7]
Olá,

Observei que primeiro item do CSV não está indo para o BIB.

Provavelmente é a tentativa de retirar o HEADER.

**Comment by jacksonpradolima** [comment]
Hi @josueresende 

Did you use the ``-header`` argument?

**Comment by josueresende** [comment]
Hi,

No, i did'nt use.

This works for me now! Thanks!
